### ISSUE TITLE
Tabs instead of spaces

### ISSUE THREAD

**Issue by CyberAndrii** [SmartlyDressedGames/RocketMod#9]
3185177630fee4f75ddb60d96e9475c98b7b0577 c3a696080ec87c90dbe74369ec6ae8041d282068 1107cac0ae7456da6f5210ae86887c872257f176 37f65bb98ab5fa3d19fc0573bb9e00aa56f38347

**Comment by SDGNelson** [comment]
Sorry about that. I have added an `.editorconfig` matching the existing code style, and corrected those tabs to spaces.
